# Generated by Django 5.0.1 on 2024-01-07 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Password'),
        ),
    ]
