# Generated by Django 5.0.1 on 2024-01-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='ashesh', max_length=13, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
