# Generated by Django 5.0.1 on 2024-01-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_face_encoding_user_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_path',
            field=models.CharField(),
        ),
    ]
