# Generated by Django 5.0.1 on 2024-01-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='img_public_id',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
