# Generated by Django 5.0.1 on 2024-02-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_username_user_img_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_attendance_taken',
            field=models.DateTimeField(null=True),
        ),
    ]
