# Generated by Django 5.0.1 on 2024-02-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_last_attendance_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_attendance_taken',
            field=models.DateField(null=True),
        ),
    ]
