# Generated by Django 5.0.1 on 2024-02-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_face', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
