# Generated by Django 5.0.1 on 2024-02-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_face', '0005_alter_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
    ]
